//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// You can write your custom code in the account-details.component.tns.ts file instead.
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, Injector } from '@angular/core';
import { Page } from 'tns-core-modules/ui/page';
import { GestureTypes, SwipeDirection, SwipeGestureEventData } from 'tns-core-modules/ui/gestures';
import { ActivatedRoute } from '@angular/router';
import { map } from 'rxjs/operators';

import { NavigationService } from '@src/app/core/services/navigation.service';
import { UtilsService } from '@src/app/core/services/utils.service';
import { DataServiceFactory } from '@src/app/core/data/data-service.factory';
import { KinveyServiceConfig } from '@src/app/core/data/kinvey-service-config';
import { EntityDataService } from '@src/app/core/data/entity-data.service';
import { Account } from '@src/app/data/account.model';
import { getAccountConfig } from '@src/app/data/account.config';

@Component({
    templateUrl: './account-details.component.html',
    styleUrls: ['./account-details.component.css']
})
export class AccountDetailsViewBaseComponent {
    public $config = {
        mobilebutton0: {
            navigateTo: {
                allowBackNavigation: false,
                parameter: ''
            }
        }
    };

    public $accoiuntService: EntityDataService<Account>;

    protected $activatedRoute: ActivatedRoute;
    protected $navigationService: NavigationService;
    protected $utilsService: UtilsService;
    protected $serviceFactory: DataServiceFactory;
    protected $page: Page;

    constructor(public injector: Injector) {
        this.$page = injector.get(Page);
        this.$activatedRoute = injector.get(ActivatedRoute);
        this.$navigationService = injector.get(NavigationService);
        this.$utilsService = injector.get(UtilsService);
        this.$serviceFactory = injector.get(DataServiceFactory);

        const dataConfig = {
            accoiunt: getAccountConfig()
        };

        this.initDataServices(dataConfig);

        this.$page.enableSwipeBackNavigation = false;
    }

    onViewLoaded({ object: view }) {
        if (view.swipeBound) {
            return;
        }

        const swipeHandler = ({ direction }: SwipeGestureEventData) => {
            if (direction === SwipeDirection.right) {
                this.$navigationService.goBack(this.$activatedRoute);
                return;
            }
        };

        view.on(GestureTypes.swipe, swipeHandler);
        view.swipeBound = true;
    }

    protected initDataServices(dataConfig: { [key: string]: KinveyServiceConfig }) {
        this.$accoiuntService = this.$serviceFactory.entity<Account>({ config: dataConfig.accoiunt, typeName: Account.name });
        this.$accoiuntService.dataState.onChanges(this.$accoiuntService.mapParams(this.$activatedRoute.queryParams));
    }
}
