//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { Routes } from '@angular/router';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { AccountDetailsViewComponent } from '@src/app/modules/main/account-details/account-details.component';
import { AccountsViewComponent } from '@src/app/modules/main/accounts/accounts.component';
import { AppointmentsViewComponent } from '@src/app/modules/main/appointments/appointments.component';
import { NewAppointmentDateViewComponent } from '@src/app/modules/main/new-appointment-date/new-appointment-date.component';
import { NewAppointmentTopicViewComponent } from '@src/app/modules/main/new-appointment-topic/new-appointment-topic.component';
import { NewAppointmentViewComponent } from '@src/app/modules/main/new-appointment/new-appointment.component';
import { NewTransactionViewComponent } from '@src/app/modules/main/new-transaction/new-transaction.component';
import { AuthenticationGuardService } from '@src/app/core/auth/authentication-guard.service';

import { config } from '@src/app/modules/main/main-routing.config';

const routes: Routes = [
    {
        path: 'new-transaction/:id',
        canActivate: [AuthenticationGuardService],
        component: NewTransactionViewComponent
    },
    {
        path: 'new-appointment-topic/:id',
        canActivate: [AuthenticationGuardService],
        component: NewAppointmentTopicViewComponent
    },
    {
        path: 'new-appointment-date/:id',
        canActivate: [AuthenticationGuardService],
        component: NewAppointmentDateViewComponent
    },
    {
        path: 'account-details/:id',
        canActivate: [AuthenticationGuardService],
        component: AccountDetailsViewComponent
    },
    {
        path: 'account-details',
        canActivate: [AuthenticationGuardService],
        component: AccountDetailsViewComponent
    },
    {
        path: 'accounts',
        canActivate: [AuthenticationGuardService],
        component: AccountsViewComponent
    },
    {
        path: 'appointments',
        canActivate: [AuthenticationGuardService],
        component: AppointmentsViewComponent
    },
    {
        path: 'new-appointment-date',
        canActivate: [AuthenticationGuardService],
        component: NewAppointmentDateViewComponent
    },
    {
        path: 'new-appointment-topic',
        canActivate: [AuthenticationGuardService],
        component: NewAppointmentTopicViewComponent
    },
    {
        path: 'new-appointment',
        canActivate: [AuthenticationGuardService],
        component: NewAppointmentViewComponent
    },
    {
        path: 'new-transaction',
        canActivate: [AuthenticationGuardService],
        component: NewTransactionViewComponent
    },
    ...config.routes
];

@NgModule({
    imports: [NativeScriptRouterModule.forChild(routes)],
    exports: [NativeScriptRouterModule]
})
export class MainRoutingModule {}
