//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { Routes } from '@angular/router';
import { NativeScriptRouterModule } from 'nativescript-angular/router';

import * as routeConfig from '@src/app/app-routing.config';

export const defaultRoute = '_app';

const routes: Routes = [
    { path: '', redirectTo: 'system', pathMatch: 'full' },
    {
        path: 'system',
        data: { enableDrawer: true },
        loadChildren: '@src/app/modules/system/system.module#SystemModule'
    },
    {
        path: 'main',
        data: { enableDrawer: true },
        loadChildren: '@src/app/modules/main/main.module#MainModule'
    },
    ...routeConfig.config.routes
];

((routeConfig as any).transformRoutes || (routes => {}))(routes);

@NgModule({
    imports: [NativeScriptRouterModule.forRoot(routes, (routeConfig as any).config.extraOptions)],
    exports: [NativeScriptRouterModule]
})
export class AppRoutingModule {}
