//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// You can write your custom code in the new-appointment-date.component.tns.ts file instead.
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, Injector, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import {
    KSFormComponent,
    FormControlOptions,
    getDefaultValidationMessages,
    getDefaultControlOptions
} from '@src/app/shared/components/mobile-form/form.component';
import { Page } from 'tns-core-modules/ui/page';
import { GestureTypes, SwipeDirection, SwipeGestureEventData } from 'tns-core-modules/ui/gestures';
import { ActivatedRoute } from '@angular/router';
import { map } from 'rxjs/operators';

import { NavigationService } from '@src/app/core/services/navigation.service';
import { UtilsService } from '@src/app/core/services/utils.service';
import { DataServiceFactory } from '@src/app/core/data/data-service.factory';
import { KinveyServiceConfig } from '@src/app/core/data/kinvey-service-config';
import { EntityDataService } from '@src/app/core/data/entity-data.service';
import { Appointment } from '@src/app/data/appointment.model';
import { getAppointmentConfig } from '@src/app/data/appointment.config';

@Component({
    templateUrl: './new-appointment-date.component.html',
    styleUrls: ['./new-appointment-date.component.css']
})
export class NewAppointmentDateViewBaseComponent implements OnInit {
    public $config = {
        mobileform0: {
            validationMessages: getDefaultValidationMessages(),
            groups: {
                appointmentFormGroup: {
                    date: getDefaultControlOptions(),
                    time: getDefaultControlOptions()
                }
            }
        }
    };

    public $appointmentService: EntityDataService<Appointment>;

    protected $activatedRoute: ActivatedRoute;
    protected $navigationService: NavigationService;
    protected $utilsService: UtilsService;
    protected $serviceFactory: DataServiceFactory;
    protected $page: Page;

    public $formBuilder: FormBuilder;
    public $appointmentFormGroup: FormGroup;

    constructor(public injector: Injector) {
        this.$page = injector.get(Page);

        this.$formBuilder = injector.get(FormBuilder);
        this.$activatedRoute = injector.get(ActivatedRoute);
        this.$navigationService = injector.get(NavigationService);
        this.$utilsService = injector.get(UtilsService);
        this.$serviceFactory = injector.get(DataServiceFactory);

        const dataConfig = {
            appointment: getAppointmentConfig()
        };

        this.initDataServices(dataConfig);

        this.$page.enableSwipeBackNavigation = false;
    }

    ngOnInit() {
        this.initFormGroups();
    }

    onViewLoaded({ object: view }) {
        if (view.swipeBound) {
            return;
        }

        const swipeHandler = ({ direction }: SwipeGestureEventData) => {
            if (direction === SwipeDirection.right) {
                this.$navigationService.goBack(this.$activatedRoute);
                return;
            }
        };

        view.on(GestureTypes.swipe, swipeHandler);
        view.swipeBound = true;
    }

    protected initDataServices(dataConfig: { [key: string]: KinveyServiceConfig }) {
        this.$appointmentService = this.$serviceFactory.entity<Appointment>({ config: dataConfig.appointment, typeName: Appointment.name });
        this.$appointmentService.dataState.onChanges(this.$appointmentService.mapParams(this.$activatedRoute.queryParams));
    }

    protected initFormGroups() {
        let date: FormControlOptions;
        let time: FormControlOptions;

        ({ date, time } = this.$config.mobileform0.groups.appointmentFormGroup);

        this.$appointmentFormGroup = this.$formBuilder.group({
            date: [date.initial, date],
            time: [time.initial, time]
        });
    }
}
