//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Kinvey } from 'kinvey-nativescript-sdk';

import { KinveyServiceConfig } from '@src/app/core/data/kinvey-service-config';
import { Appointment } from '@src/app/data/appointment.model';

export function getAppointmentConfig(): KinveyServiceConfig {
    return {
        dataProviderName: 'DefaultDataProvider',
        serverOperations: true,
        createModel: () => new Appointment(),
        mapData: dataItem => {
            if (dataItem.date) {
                dataItem.date = new Date(dataItem.date);
            }
            if (dataItem.time) {
                dataItem.time = new Date(dataItem.time);
            }

            return dataItem;
        },
        collection: 'appointments',
        dataStoreType: Kinvey.DataStoreType.Network,
        loadOnDemand: true
    };
}
