//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
export class Appointment {
    public _id: string;
    public date: Date;
    public time: Date;
    public locationId: string;
    public approved: boolean;
    public topic: string;
    public active: boolean;
}
